sudo: required
services:
- docker
language: bash
env:
- TAG="icemanaf/serialport-event-forwarder"
script:
# build image
- docker build -t $TAG .
# push to docker
- echo $TRAVIS_TAG
- echo $TRAVIS_BRANCH
- echo $TRAVIS_BUILD_NUMBER
#Login to Docker Hub
- >
  if [ $TRAVIS_BRANCH=="master" ];
  then
   docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
   docker tag $TAG $TAG:$TRAVIS_BUILD_NUMBER
   docker push $TAG:$TRAVIS_BUILD_NUMBER
   docker push $TAG
  fi